name: 'my_dbt_demo'
version: '1.0.0'
dbt-cloud:
  project-id: 70403103940890
profile: 'zurich_ntt_dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  my_dbt_demo:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
